version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: lumen
      DB_USERNAME: lumen
      DB_PASSWORD: lumen
    volumes:
      - .:/var/www/html/v1/notifications
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: lumen
      POSTGRES_USER: lumen
      POSTGRES_PASSWORD: lumen

  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - app
