version: '3'
services:
  app:
    build: .
    image: myapp
    container_name: myapp
    restart: always
    ports:
      - "80:80"
    env_file: .env
    environment:
      APP_ENV: production
  db:
    image: postgres:12.7-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
